### ISSUE TITLE
Distorted Flipping Animation 

### ISSUE THREAD

**Issue by Moqri** [hilios/jQuery.countdown#168] opened 2015-11-24 22:29 UTC
When I use the main example html and css I get this:
![untitled](https://cloud.githubusercontent.com/assets/4342458/11382616/f432e5b2-92d0-11e5-9f74-3f9f645ffd90.png)

**Comment by TimSmith714** [comment] 2015-11-24 22:36
Hi, 
I fixed this by adjusting the height of the divs containing each set of numbers from 95px to 79px

    .main-example .time {
      height: 79px;
     }

You can see it in action (and the overridden height) at
http://cubittandwest.co.uk/black-friday-offer/

**Comment by Moqri** [comment] 2015-11-24 22:50
Thanks, yes that works for me too!
Another issue that I see in the example and your website is this one:
![untitled](https://cloud.githubusercontent.com/assets/4342458/11383092/d7ee39c6-92d3-11e5-97bc-360b97c0a66f.png)

**Comment by TimSmith714** [comment] 2015-11-24 22:52
Not so good! We'd seen it briefly in the office but only on Safari on OS X El Capitan. I'm using Opera on Win8.1 here so it might be a bigger problem than I'd hoped.

**Comment by Moqri** [comment] 2015-11-24 23:02
I see this on Windows 8, Google Chrome browser

**Comment by hilios** [comment] 2015-11-26 14:44
What you are experiencing I believe is an hardware acceleration problem caused by your OS. For instance, I can't reproduce the bug both my Ubuntu and Mac (since Snow Leopard).

See the duplicated #100

**Comment by TimSmith714** [comment] 2015-11-26 15:46
Thanks for the link to #100 
I've updated the perspective to 479px on the countdown pages and it seems to have fixed it.

**Comment by hilios** [comment] 2015-11-30 13:06
Cool @TimSmith714 if you could provide an pull request to the `gh-pages` with the fix would be great!

**Comment by hilios** [comment] 2015-12-01 01:52
I will close this since we have a duplicate, if any of you guys need help, do it at the #100

**Closed by hilios** 2015-12-01 01:52 UTC
